// <auto-generated />
using System;
using ArchieMate.Chatbot.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArchieMate.Chatbot.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    [Migration("20230111200210_AddTTSWidgetConfiguration")]
    partial class AddTTSWidgetConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchieMate.Chatbot.Models.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Join")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("ArchieMate.Chatbot.Models.ChannelVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("ChannelVariables");
                });

            modelBuilder.Entity("ArchieMate.Chatbot.Models.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("ArchieMate.Chatbot.Models.TTSWidgetConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowEmoteOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("Censoring")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<long>("DelayBetweenMessages")
                        .HasColumnType("bigint");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<long>("MaxDuration")
                        .HasColumnType("bigint");

                    b.Property<bool>("OnlyFromMentions")
                        .HasColumnType("boolean");

                    b.Property<long>("VolumePercent")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TTSWidgetConfigurations");
                });

            modelBuilder.Entity("ArchieMate.Chatbot.Models.ChannelVariable", b =>
                {
                    b.HasOne("ArchieMate.Chatbot.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("ArchieMate.Chatbot.Models.Command", b =>
                {
                    b.HasOne("ArchieMate.Chatbot.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });
#pragma warning restore 612, 618
        }
    }
}
