# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  test:
    image: archiemate/test
    container_name: archiemate_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
