name: CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Set Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: vite

      - name: Build, tag and push Docker image to Docker Hub
        run: sbt "ArchieMateCrossJVM / Docker / publish"